repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.2.0'
    hooks:
    -   id: double-quote-string-fixer
    -   id: end-of-file-fixer
    -   id: fix-encoding-pragma
    -   id: mixed-line-ending
    -   id: trailing-whitespace

-   repo: https://github.com/pre-commit/mirrors-yapf
    rev: 'v0.32.0'
    hooks:
    -   id: yapf
        name: yapf
        types: [python]
        args: ['-i']
        additional_dependencies: ['toml']

-   repo: https://github.com/PyCQA/pydocstyle
    rev: '6.1.1'
    hooks:
    -   id: pydocstyle
        exclude: >
            (?x)^(
                aiida_quantumespresso_hp/workflows/hubbard.py|
            )$
        additional_dependencies: ['toml']

-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint
        types: [python]
        language: system
        args: [
            '--max-line-length=120',
            '--disable=bad-continuation',
            '--disable=consider-using-f-string',
            '--disable=duplicate-code',
            '--disable=import-outside-toplevel',
            '--disable=inconsistent-return-statements',
            '--disable=invalid-name',
            '--disable=no-member',
            '--disable=too-many-arguments',
            '--disable=too-many-branches',
            '--disable=too-many-locals',
        ]
