[build-system]
requires = ['hatchling']
build-backend = 'hatchling.build'

[project]
name = 'aiida-hubbard'
dynamic = ['version']
description = 'AiiDA plugin for the first-principles calculation of Hubbard parameters'
authors = [
    {name = 'Lorenzo Bastonero', email = 'lbastone@uni-bremen.de'},
    {name = 'Sebastiaan P. Huber', email = 'mail@sphuber.net'}
]
readme = 'README.md'
license = {file = 'LICENSE.txt'}
classifiers = [
    'Development Status :: 5 - Production/Stable',
    'Framework :: AiiDA',
    'License :: Free To Use But Restricted',
    'Operating System :: POSIX :: Linux',
    'Operating System :: MacOS :: MacOS X',
    'Programming Language :: Python',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
    'Programming Language :: Python :: 3.12',
    'Programming Language :: Python :: 3.13',
    'Programming Language :: Python :: 3.14',
]
keywords = ['aiida', 'workflows']
requires-python = '>=3.10'
dependencies = [
    'aiida-core~=2.8',
    'aiida-quantumespresso~=5.0',
]

[project.urls]
Home = 'https://github.com/aiidateam/aiida-hubbard'
Source = 'https://github.com/aiidateam/aiida-hubbard'
Documentation = 'https://aiida-hubbard.readthedocs.io'

[project.optional-dependencies]
pre-commit = [
    'pre-commit>=4.3.0',
]
tests = [
    'pgtest~=1.3',
    'pytest~=8.4',
    'coverage[toml]',
    'pytest-cov',
    'pytest-regressions~=2.8',
    'pytest-timeout',
]
docs = [
    'myst-nb~=1.0',
    'jupytext>=1.11.2,<1.15.0',
    'sphinx~=6.2.1',
    'sphinx-copybutton~=0.5.2',
    'sphinx-book-theme~=1.0.1',
    'sphinx-click~=4.4.0',
    'sphinx-design~=0.4.1',
    'sphinxcontrib-details-directive~=0.1.0',
    'sphinx-autoapi~=3.0.0',
    'astroid<3.0',
    'myst-parser~=3.0.0',
    'sphinx-togglebutton',
]

[dependency-groups]
dev = [
  "aiida-hubbard[docs,tests,pre-commit]",
]

[project.scripts]
aiida-hubbard = 'aiida_hubbard.cli:cmd_root'

[project.entry-points.'aiida.calculations']
'quantumespresso.hp' = 'aiida_hubbard.calculations.hp:HpCalculation'

[project.entry-points.'aiida.parsers']
'quantumespresso.hp' = 'aiida_hubbard.parsers.hp:HpParser'

[project.entry-points.'aiida.workflows']
'quantumespresso.hp.main' = 'aiida_hubbard.workflows.hp.main:HpWorkChain'
'quantumespresso.hp.parallelize_atoms' = 'aiida_hubbard.workflows.hp.parallelize_atoms:HpParallelizeAtomsWorkChain'
'quantumespresso.hp.parallelize_qpoints' = 'aiida_hubbard.workflows.hp.parallelize_qpoints:HpParallelizeQpointsWorkChain'
'quantumespresso.hp.base' = 'aiida_hubbard.workflows.hp.base:HpBaseWorkChain'
'quantumespresso.hp.hubbard' = 'aiida_hubbard.workflows.hubbard:SelfConsistentHubbardWorkChain'

[tool.hatch.build.targets.wheel]
packages = ['src/aiida_hubbard']

[tool.hatch.build.targets.sdist]
exclude = [
  '.github/',
  '.gitignore',
  '.pre-commit-config.yaml',
  'docs/',
  'examples/',
  'tests/',
]

[tool.hatch.version]
path = 'src/aiida_hubbard/__init__.py'

[tool.hatch.envs.default]
installer = 'uv'

[tool.hatch.envs.pre-commit]
features = ["pre-commit"]
scripts.install = 'pre-commit install'
scripts.run = 'pre-commit run {args}'

[tool.hatch.envs.hatch-test]
features = ["tests"]
randomize = false
parallel = false
run = "pytest {args}"

[[tool.hatch.envs.hatch-test.matrix]]
python = ["3.10", "3.11", "3.12", "3.13", "3.14"]

[tool.hatch.envs.docs]
features = ["docs"]
scripts.clean = 'make -C docs clean'
scripts.build = 'make -C docs html'
scripts.view = 'make -C docs view'

[tool.coverage.run]
# Configuration of [coverage.py](https://coverage.readthedocs.io)
# reporting which lines of your plugin are covered by tests
source = ["src/aiida_hubbard"]

[tool.pytest.ini_options]
# Configuration for [pytest](https://docs.pytest.org)
python_files = "test_*.py example_*.py"
filterwarnings = [
    "ignore::DeprecationWarning:aiida:",
    "ignore:Creating AiiDA configuration folder:",
    "ignore::DeprecationWarning:plumpy:",
    "ignore::DeprecationWarning:yaml:",
]
# testpaths = 'tests'

[tool.ruff]
line-length = 120
extend-exclude = ['*.ipynb']
lint.ignore = [
    "ARG002",  # https://docs.astral.sh/ruff/rules/unused-method-argument/
    "ARG004",  # https://docs.astral.sh/ruff/rules/unused-static-method-argument/
    "B028",    # https://docs.astral.sh/ruff/rules/no-explicit-stacklevel/
    "BLE001",  # https://docs.astral.sh/ruff/rules/blind-except/
    "EM101",   # https://docs.astral.sh/ruff/rules/raw-string-in-exception/
    "EM102",   # https://docs.astral.sh/ruff/rules/f-string-in-exception/
    "EXE001",  # https://docs.astral.sh/ruff/rules/shebang-not-executable/
    "FA100",   # https://docs.astral.sh/ruff/rules/future-rewritable-type-annotation/
    "FBT001",  # https://docs.astral.sh/ruff/rules/boolean-type-hint-positional-argument/
    "FBT002",  # https://docs.astral.sh/ruff/rules/boolean-default-value-positional-argument/
    "G004",    # https://docs.astral.sh/ruff/rules/logging-f-string/
    "N805",    # https://docs.astral.sh/ruff/rules/invalid-first-argument-name-for-method/
    "PERF401", # https://docs.astral.sh/ruff/rules/manual-list-comprehension/
    "PLR2004", # https://docs.astral.sh/ruff/rules/magic-value-comparison/
    "RUF005",  # https://docs.astral.sh/ruff/rules/collection-literal-concatenation/
    "RUF012",  # https://docs.astral.sh/ruff/rules/mutable-class-default/
    "RET503",  # https://docs.astral.sh/ruff/rules/implicit-return/
    "S110",    # https://docs.astral.sh/ruff/rules/try-except-pass/
    "S318",    # https://docs.astral.sh/ruff/rules/suspicious-xml-mini-dom-usage/
    "S314",    # https://docs.astral.sh/ruff/rules/suspicious-xml-element-tree-usage/
    "TID252",  # https://docs.astral.sh/ruff/rules/relative-imports/
    "TRY004",  # https://docs.astral.sh/ruff/rules/type-check-without-type-error/
    "TRY003",  # https://docs.astral.sh/ruff/rules/raise-vanilla-args/
    "TRY301",  # https://docs.astral.sh/ruff/rules/raise-within-try/
]
[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = [
    "INP001",  # https://docs.astral.sh/ruff/rules/implicit-namespace-package/
    "PT009",   # https://docs.astral.sh/ruff/rules/pytest-unittest-assertion/
    "PT011",   # https://docs.astral.sh/ruff/rules/pytest-raises-too-broad/
    "PT027",   # https://docs.astral.sh/ruff/rules/pytest-unittest-raises-assertion/
    "S101",    # https://docs.astral.sh/ruff/rules/assert/
    "SLF001",  # https://docs.astral.sh/ruff/rules/private-member-access/
]
"src/aiida_hubbard/cli/**/*.py" = ["ALL"]
"docs/**/*.py" = ["ALL"]
"examples/**/*.py" = ["ALL"]

[tool.ruff.format]
quote-style = "single"
