default_inputs:
    clean_workdir: True
    only_initialization: False
    hp:
        metadata:
            options:
                resources:
                    num_machines: 1
                max_wallclock_seconds: 43200  # Twelve hours
                withmpi: True
        parameters:
            INPUTHP:
                conv_thr_chi: 5.e-6
        qpoints:
            - 2
            - 2
            - 2
        settings:
            parent_folder_symlink: true

default_protocol: moderate
protocols:
    moderate:
        description: 'Protocol to perform the computation at normal precision at moderate computational cost.'
    precise:
        description: 'Protocol to perform the computation at high precision at higher computational cost.'
        qpoints:
            - 3
            - 3
            - 3
        hp:
            parameters:
                INPUTHP:
                    conv_thr_chi: 1.e-8
    fast:
        description: 'Protocol to perform the computation at low precision at minimal computational cost for testing purposes.'
        qpoints:
            - 1
            - 1
            - 1
        hp:
            parameters:
                INPUTHP:
                    conv_thr_chi: 1.e-4
